
const {createClient}=supabase;
const db=createClient(CRM_CONFIG.url,CRM_CONFIG.key);
let session=null, page='dashboard', customers=[], followups=[], records={quotes:[],pis:[],orders:[],shipments:[],samples:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function today(){let d=new Date();d.setHours(0,0,0,0);return d} function days(s){if(!s)return 9999;return Math.round((new Date(s+'T00:00:00')-today())/864e5)}
function status(c){let d=days(c.next_follow);if(d<0)return['已逾期','status-overdue'];if(d===0)return['今日跟进','status-today'];if(d<=3)return[d+'天内','status-soon'];return['待跟进','']}
function fmt(s){return s?new Date(s+'T00:00:00').toLocaleDateString('zh-CN'):'—'}
function money(n){return '$'+Number(n||0).toLocaleString()}
const pageMeta={dashboard:['概览','欢迎回来，今天优先处理最有价值的客户。'],today:['今日待跟','逾期、今日和未来3天的客户。'],customers:['客户CRM','管理客户画像、阶段和完整时间轴。'],quotes:['报价管理','统一管理报价金额、版本和状态。'],pi:['PI管理','管理形式发票、付款条件和确认状态。'],orders:['订单管理','从确认到生产的全过程。'],shipments:['发货管理','记录物流、清关和签收。'],samples:['样品管理','跟踪样品寄送与反馈。'],analytics:['数据统计','成交漏斗和销售预测。'],ai:['AI助手','本地规则分析客户并生成跟进话术。'],data:['数据管理','Excel导入导出与一键备份。']};

async function init(){
 const {data:{session:s}}=await db.auth.getSession(); setSession(s);
 db.auth.onAuthStateChange((_e,s)=>setSession(s));
}
async function setSession(s){session=s;$('#authScreen').classList.toggle('hidden',!!s);$('#app').classList.toggle('hidden',!s);if(s){$('#userEmail').textContent=s.user.email;await loadAll();render()}}
let authMode='login';$$('[data-auth]').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));$('#authForm button').textContent=authMode==='login'?'登录':'注册'});
$('#authForm').onsubmit=async e=>{e.preventDefault();let email=$('#authEmail').value,password=$('#authPassword').value;let r=authMode==='login'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password});if(r.error)return toast(r.error.message);toast(authMode==='login'?'登录成功':'注册成功，请检查邮箱确认')};
$('#logoutBtn').onclick=()=>db.auth.signOut();$('#themeBtn').onclick=()=>{let d=document.documentElement;d.dataset.theme=d.dataset.theme==='dark'?'':'dark';localStorage.setItem('crm_theme',d.dataset.theme);};document.documentElement.dataset.theme=localStorage.getItem('crm_theme')||'';
$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;$$('#nav button').forEach(x=>x.classList.toggle('active',x===b));render()};
$('#globalAdd').onclick=()=>customerForm();$('#modalClose').onclick=()=>closeModal();

async function loadAll(){
 let [c,f,q,p,o,s,sa]=await Promise.all([
 db.from('customers').select('*').order('next_follow',{ascending:true,nullsFirst:false}),
 db.from('followups').select('*').order('contact_date',{ascending:false}),
 db.from('quotes').select('*').order('created_at',{ascending:false}),
 db.from('pis').select('*').order('created_at',{ascending:false}),
 db.from('orders').select('*').order('created_at',{ascending:false}),
 db.from('shipments').select('*').order('created_at',{ascending:false}),
 db.from('samples').select('*').order('created_at',{ascending:false})]);
 for(const r of [c,f,q,p,o,s,sa])if(r.error){toast(r.error.message);console.error(r.error)}
 customers=c.data||[];followups=f.data||[];records={quotes:q.data||[],pis:p.data||[],orders:o.data||[],shipments:s.data||[],samples:sa.data||[]};
}
function render(){let [t,sub]=pageMeta[page];$('#pageTitle').textContent=t;$('#pageSub').textContent=sub;$('#globalAdd').style.display=['dashboard','today','customers'].includes(page)?'':'none';let fn={dashboard:dashboardPage,today:todayPage,customers:customersPage,quotes:()=>modulePage('quotes','报价'),pi:()=>modulePage('pis','PI'),orders:()=>modulePage('orders','订单'),shipments:()=>modulePage('shipments','发货'),samples:()=>modulePage('samples','样品'),analytics:analyticsPage,ai:aiPage,data:dataPage}[page];$('#content').innerHTML=fn();bindPage()}
function dashboardPage(){
 let a=customers.filter(x=>x.grade==='A').length,td=customers.filter(x=>days(x.next_follow)===0).length,od=customers.filter(x=>days(x.next_follow)<0).length,soon=customers.filter(x=>days(x.next_follow)>=0&&days(x.next_follow)<=3).length;
 let pri=customers.filter(x=>days(x.next_follow)<=3).slice(0,6);
 return `<div class=kpis><div class="card kpi blue"><label>A类客户</label><strong>${a}</strong></div><div class="card kpi teal"><label>今日跟进</label><strong>${td}</strong></div><div class="card kpi orange"><label>已逾期</label><strong>${od}</strong></div><div class="card kpi purple"><label>3天内跟进</label><strong>${soon}</strong></div></div>
 <div class="card panel"><div class=panel-head><h3>优先跟进</h3><button class=ghost data-go=today>查看全部</button></div>${pri.length?pri.map(followCard).join(''):'<div class=empty>暂无优先跟进</div>'}</div>
 <div class="card panel"><div class=panel-head><h3>销售预测</h3></div><div class=kpis><div class=kpi><label>预计金额</label><strong>${money(customers.reduce((a,c)=>a+Number(c.amount||0)*Number(c.probability||0)/100,0))}</strong></div><div class=kpi><label>已报价客户</label><strong>${customers.filter(c=>c.stage==='已报价').length}</strong></div><div class=kpi><label>PI确认</label><strong>${customers.filter(c=>c.stage==='PI确认').length}</strong></div><div class=kpi><label>已成交</label><strong>${customers.filter(c=>c.stage==='已成交').length}</strong></div></div></div>`
}
function followCard(c){let s=status(c);return `<div class="follow-card ${c.grade}"><div class=follow-top><div><div class=name>${esc(c.name)}</div><div class=sub>${esc(c.platform||'')} · ${esc(c.stage||'')} · ${esc(c.products||'')}</div></div><div><span class="badge grade-${c.grade}">${c.grade}类</span><div class="${s[1]}" style="margin-top:8px">${fmt(c.next_follow)} · ${s[0]}</div></div></div><p><b>下一步：</b>${esc(c.next_action||'未填写')}</p><div class=row-actions><button class=ghost data-detail="${c.id}">查看详情</button><button class=primary data-follow="${c.id}">记录跟进</button></div></div>`}
function todayPage(){let x=customers.filter(c=>days(c.next_follow)<=3);return x.length?x.map(followCard).join(''):'<div class="card empty">暂无需要跟进的客户</div>'}
function customersPage(){return `<div class="card panel"><div class=toolbar><input id=search placeholder="搜索客户、国家、产品、顾虑"><select id=gradeFilter><option value="">全部等级</option><option>A</option><option>B</option><option>C</option></select><select id=stageFilter><option value="">全部阶段</option>${['新询盘','需求确认','已报价','等确认','PI确认','已成交','暂缓'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class=table-wrap><table><thead><tr><th>客户</th><th>等级</th><th>阶段</th><th>下次跟进</th><th>状态</th><th>概率</th><th>下一步</th><th></th></tr></thead><tbody id=customerRows>${customerRows(customers)}</tbody></table></div></div>`}
function customerRows(arr){return arr.map(c=>{let s=status(c);return `<tr><td><div class=name>${esc(c.name)}</div><div class=sub>${esc(c.country||'')} · ${esc(c.platform||'')} · ${esc(c.products||'')}</div></td><td><span class="badge grade-${c.grade}">${c.grade}</span></td><td>${esc(c.stage)}</td><td>${fmt(c.next_follow)}</td><td class="${s[1]}">${s[0]}</td><td><b>${c.probability||0}%</b><div class=progress><span style="width:${c.probability||0}%"></span></div></td><td>${esc(c.next_action||'—')}</td><td><button class=ghost data-detail="${c.id}">查看</button></td></tr>`}).join('')}
const moduleConfig={quotes:{table:'quotes',fields:['number','amount','status'],heads:['报价号','金额','状态']},pis:{table:'pis',fields:['number','amount','status'],heads:['PI号','金额','状态']},orders:{table:'orders',fields:['number','amount','status'],heads:['订单号','金额','状态']},shipments:{table:'shipments',fields:['tracking_no','carrier','status'],heads:['运单号','承运商','状态']},samples:{table:'samples',fields:['item','tracking_no','status'],heads:['样品','运单号','状态']}};
function modulePage(key,label){let cfg=moduleConfig[key],arr=records[key]||[];return `<div class="card panel"><div class=panel-head><h3>${label}列表</h3><button class=primary data-add-module="${key}">＋ 新增${label}</button></div><div class=table-wrap><table><thead><tr><th>客户</th>${cfg.heads.map(x=>`<th>${x}</th>`).join('')}<th>日期</th><th>备注</th><th></th></tr></thead><tbody>${arr.map(r=>`<tr><td>${esc(customers.find(c=>c.id===r.customer_id)?.name||'')}</td>${cfg.fields.map(f=>`<td>${f==='amount'?money(r[f]):esc(r[f]||'—')}</td>`).join('')}<td>${fmt((r.created_at||'').slice(0,10))}</td><td>${esc(r.notes||'')}</td><td><button class="ghost danger" data-delete-module="${key}" data-id="${r.id}">删除</button></td></tr>`).join('')||'<tr><td colspan=8 class=empty>暂无记录</td></tr>'}</tbody></table></div></div>`}
function analyticsPage(){let stages=['新询盘','需求确认','已报价','等确认','PI确认','已成交'];let counts=stages.map(s=>customers.filter(c=>c.stage===s).length),max=Math.max(1,...counts);return `<div class=kpis><div class="card kpi"><label>客户总数</label><strong>${customers.length}</strong></div><div class="card kpi"><label>预计加权金额</label><strong>${money(customers.reduce((a,c)=>a+Number(c.amount||0)*Number(c.probability||0)/100,0))}</strong></div><div class="card kpi"><label>订单数</label><strong>${records.orders.length}</strong></div><div class="card kpi"><label>跟进记录</label><strong>${followups.length}</strong></div></div><div class="card panel"><div class=panel-head><h3>成交漏斗</h3></div><div class=funnel>${stages.map((s,i)=>`<div class=funnel-col><div class=funnel-bar style="height:${30+counts[i]/max*150}px"></div><b>${counts[i]}</b><span>${s}</span></div>`).join('')}</div></div>`}
function aiPage(){return `<div class="card panel"><div class=ai-box><div><h3>粘贴客户聊天摘要</h3><textarea id=aiInput style="width:100%;height:220px" placeholder="例如：客户担心清关费用，计划8月初购买，已询问海运和快递时效……"></textarea><div class=form-actions><button class=primary id=analyzeBtn>生成分析与话术</button></div><p class=sub>当前为本地规则分析，不会将内容发送给第三方。正式接入大模型需要增加服务器端API。</p></div><div><h3>分析结果</h3><div class=ai-output id=aiOutput>等待输入……</div></div></div></div>`}
function dataPage(){return `<div class="card panel"><div class=panel-head><h3>数据管理</h3></div><div class=row-actions style="flex-wrap:wrap"><button class=primary id=seedBtn>导入现有9位客户</button><button class=ghost id=excelBtn>导出Excel</button><button class=ghost id=backupBtn>一键备份JSON</button><button class=ghost id=restoreBtn>恢复JSON</button><input type=file id=restoreFile accept=.json hidden></div><p class=sub style="margin-top:15px">备份包含客户、跟进、报价、PI、订单、发货和样品数据。</p></div>`}
function bindPage(){
 $$('[data-go]').forEach(b=>b.onclick=()=>{page=b.dataset.go;render()});$$('[data-detail]').forEach(b=>b.onclick=()=>customerDetail(Number(b.dataset.detail)));$$('[data-follow]').forEach(b=>b.onclick=()=>followForm(Number(b.dataset.follow)));
 if($('#search')){let filter=()=>{let q=$('#search').value.toLowerCase(),g=$('#gradeFilter').value,s=$('#stageFilter').value,a=customers.filter(c=>(!q||JSON.stringify(c).toLowerCase().includes(q))&&(!g||c.grade===g)&&(!s||c.stage===s));$('#customerRows').innerHTML=customerRows(a);bindPage()};$('#search').oninput=filter;$('#gradeFilter').onchange=filter;$('#stageFilter').onchange=filter}
 $$('[data-add-module]').forEach(b=>b.onclick=()=>moduleForm(b.dataset.addModule));$$('[data-delete-module]').forEach(b=>b.onclick=()=>deleteModule(b.dataset.deleteModule,Number(b.dataset.id)));
 if($('#analyzeBtn'))$('#analyzeBtn').onclick=analyzeLocal;if($('#seedBtn'))$('#seedBtn').onclick=seedData;if($('#excelBtn'))$('#excelBtn').onclick=exportExcel;if($('#backupBtn'))$('#backupBtn').onclick=backup;if($('#restoreBtn'))$('#restoreBtn').onclick=()=>$('#restoreFile').click();if($('#restoreFile'))$('#restoreFile').onchange=restore;
}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<div class=modal-body>${html}</div>`;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
function customerForm(c={}){openModal(c.id?'编辑客户':'新增客户',`<form id=customerForm><div class=form-grid>${field('name','客户名称',c.name,true)}${selectField('platform','平台',['WA','IG','Email','Alibaba','其他'],c.platform)}${field('country','国家/地区',c.country)}${field('products','产品需求',c.products)}${selectField('grade','客户等级',['A','B','C'],c.grade||'B')}${selectField('stage','当前阶段',['新询盘','需求确认','已报价','等确认','PI确认','已成交','暂缓'],c.stage||'新询盘')}${field('last_contact','最后联系','',false,'date',c.last_contact)}${field('next_follow','下次跟进','',false,'date',c.next_follow)}${field('probability','成交概率%',c.probability||50,false,'number')}${field('amount','预计金额USD',c.amount||'',false,'number')}${area('profile','客户画像',c.profile)}${area('grade_reason','归类原因',c.grade_reason)}${area('concern','核心顾虑',c.concern)}${area('next_action','下一步行动',c.next_action)}${area('notes','备注',c.notes)}</div><div class=form-actions>${c.id?'<button type=button class="ghost danger" id=deleteCustomer>删除</button>':''}<button type=button class=ghost id=cancel>取消</button><button class=primary>保存</button></div></form>`);
 $('#cancel').onclick=closeModal;if(c.id)$('#deleteCustomer').onclick=()=>deleteCustomer(c.id);$('#customerForm').onsubmit=e=>saveCustomer(e,c.id)}
function field(n,l,v='',req=false,type='text',override){return `<div class=field><label>${l}</label><input name=${n} type=${type} value="${esc(override??v)}" ${req?'required':''}></div>`}function area(n,l,v=''){return `<div class="field full"><label>${l}</label><textarea name=${n}>${esc(v||'')}</textarea></div>`}function selectField(n,l,opts,v){return `<div class=field><label>${l}</label><select name=${n}>${opts.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></div>`}
async function saveCustomer(e,id){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.probability=Number(o.probability||0);o.amount=o.amount?Number(o.amount):null;o.user_id=session.user.id;let r=id?await db.from('customers').update(o).eq('id',id):await db.from('customers').insert(o);if(r.error)return toast(r.error.message);toast('已保存');closeModal();await loadAll();render()}
async function deleteCustomer(id){if(!confirm('确定删除客户及其关联记录？'))return;let r=await db.from('customers').delete().eq('id',id);if(r.error)return toast(r.error.message);closeModal();await loadAll();render()}
async function customerDetail(id){let c=customers.find(x=>x.id===id),fs=followups.filter(x=>x.customer_id===id);openModal(c.name,`<div class=detail-grid><div class=detail-box><label>等级 / 阶段</label><p><span class="badge grade-${c.grade}">${c.grade}类</span>　${esc(c.stage)}</p></div><div class=detail-box><label>成交概率 / 金额</label><p>${c.probability||0}%　${money(c.amount)}</p></div><div class="detail-box full"><label>客户画像</label><p>${esc(c.profile||'—')}</p></div><div class="detail-box full"><label>核心顾虑</label><p>${esc(c.concern||'—')}</p></div><div class="detail-box full"><label>下一步行动</label><p>${esc(c.next_action||'—')}</p></div></div><div class=panel-head style="margin-top:22px"><h3>跟进时间轴</h3><div><button class=ghost id=editClient>编辑</button> <button class=primary id=addFollow>记录跟进</button></div></div><div class=timeline>${fs.map(f=>`<div class=timeline-item><h4>${new Date(f.contact_date).toLocaleString('zh-CN')} · ${esc(f.channel||'跟进')}</h4><p>${esc(f.summary||'')}</p>${f.customer_message?`<p><b>客户：</b>${esc(f.customer_message)}</p>`:''}${f.our_message?`<p><b>我方：</b>${esc(f.our_message)}</p>`:''}<p><b>下一步：</b>${esc(f.next_action||'—')}　${f.next_follow?'｜ '+fmt(f.next_follow):''}</p></div>`).join('')||'<div class=empty>暂无跟进记录</div>'}</div>`);$('#editClient').onclick=()=>customerForm(c);$('#addFollow').onclick=()=>followForm(id)}
function followForm(id){let c=customers.find(x=>x.id===id);openModal('记录跟进 · '+c.name,`<form id=followForm><div class=form-grid>${selectField('channel','渠道',['WA','IG','Email','电话','其他'],c.platform)}${field('contact_date','联系时间','',false,'datetime-local',new Date().toISOString().slice(0,16))}${area('customer_message','客户回复', '')}${area('our_message','我方发送', '')}${area('summary','本次摘要','')}${area('concern','最新顾虑',c.concern)}${area('next_action','下一步行动',c.next_action)}${field('next_follow','下次跟进','',false,'date',c.next_follow)}</div><div class=form-actions><button type=button class=ghost id=cancel>取消</button><button class=primary>保存跟进</button></div></form>`);$('#cancel').onclick=closeModal;$('#followForm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.customer_id=id;o.user_id=session.user.id;let r=await db.from('followups').insert(o);if(r.error)return toast(r.error.message);await db.from('customers').update({last_contact:o.contact_date.slice(0,10),next_follow:o.next_follow,concern:o.concern,next_action:o.next_action}).eq('id',id);toast('跟进已记录');closeModal();await loadAll();render()}}
function moduleForm(key){let cfg=moduleConfig[key],label={quotes:'报价',pis:'PI',orders:'订单',shipments:'发货',samples:'样品'}[key];openModal('新增'+label,`<form id=moduleForm><div class=form-grid>${selectField('customer_id','客户',customers.map(c=>c.id+'|'+c.name),'')}${cfg.fields.map((f,i)=>field(f,cfg.heads[i],'',false,f==='amount'?'number':'text')).join('')}${area('notes','备注','')}</div><div class=form-actions><button type=button class=ghost id=cancel>取消</button><button class=primary>保存</button></div></form>`);let sel=$('[name=customer_id]');[...sel.options].forEach(o=>{let [id,...n]=o.textContent.split('|');o.value=id;o.textContent=n.join('|')});$('#cancel').onclick=closeModal;$('#moduleForm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.customer_id=Number(o.customer_id);o.user_id=session.user.id;if(o.amount)o.amount=Number(o.amount);let r=await db.from(cfg.table).insert(o);if(r.error)return toast(r.error.message);closeModal();toast('已保存');await loadAll();render()}}
async function deleteModule(key,id){if(!confirm('确定删除？'))return;let r=await db.from(moduleConfig[key].table).delete().eq('id',id);if(r.error)return toast(r.error.message);await loadAll();render()}
function analyzeLocal(){let t=$('#aiInput').value.trim();if(!t)return toast('请先输入聊天摘要');let score=40,reasons=[],concerns=[];if(/报价|price|quote/i.test(t)){score+=10;reasons.push('已涉及报价')}if(/PI|付款|payment|货代|forwarder/i.test(t)){score+=25;reasons.push('进入执行阶段')}if(/开业|月底|下月|8月|9月|deadline/i.test(t)){score+=10;reasons.push('有明确时间节点')}if(/进口|清关|税|运费|运输|shipping/i.test(t))concerns.push('物流、进口或成本顾虑');if(/已读未回|不回复|未读/i.test(t)){score-=15;reasons.push('互动热度偏低')}score=Math.max(10,Math.min(95,score));let grade=score>=75?'A':score>=45?'B':'C';let action=concerns.length?'优先解释费用构成、清关责任与到门方案，并给出两个可比较的运输选项。':'用轻量问题确认采购时间、数量和当前决策障碍。';$('#aiOutput').textContent=`客户等级：${grade}类\n成交概率：${score}%\n\n判断依据：${reasons.join('；')||'信息有限，建议继续确认需求'}\n核心顾虑：${concerns.join('；')||'暂未识别'}\n下一步行动：${action}\n\n建议跟进话术：\nHi, just checking in to see how things are going with your project. Is there anything about the product, shipping, or quotation that you would like me to clarify? I’m happy to help you compare the best option.`}
async function seedData(){if(customers.length&&!confirm('当前已有客户，仍要继续导入吗？'))return;let data=SEED_CLIENTS.map(x=>({...x,user_id:session.user.id}));let r=await db.from('customers').insert(data);if(r.error)return toast(r.error.message);toast('已导入9位客户');await loadAll();render()}
function exportExcel(){let wb=XLSX.utils.book_new();let sheets={客户:customers,跟进:followups,报价:records.quotes,PI:records.pis,订单:records.orders,发货:records.shipments,样品:records.samples};for(let [n,d] of Object.entries(sheets))XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d),n);XLSX.writeFile(wb,'PACKROVE_CRM.xlsx')}
async function backup(){let data={version:2,exported_at:new Date().toISOString(),customers,followups,...records};download(JSON.stringify(data,null,2),'PACKROVE_CRM_BACKUP.json','application/json')}
function download(content,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function restore(e){let f=e.target.files[0];if(!f)return;try{let d=JSON.parse(await f.text());for(let [table,items] of Object.entries({customers:d.customers,followups:d.followups,quotes:d.quotes,pis:d.pis,orders:d.orders,shipments:d.shipments,samples:d.samples})){if(!Array.isArray(items))continue;let cleaned=items.map(({id,created_at,updated_at,...x})=>({...x,user_id:session.user.id}));if(cleaned.length){let r=await db.from(table).insert(cleaned);if(r.error)throw r.error}}toast('恢复完成');await loadAll();render()}catch(err){toast('恢复失败：'+err.message)}}
init();
