
-- PACKROVE CRM V2 数据库升级脚本
-- 在 Supabase SQL Editor 中完整运行一次

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  name text not null,
  platform text,
  country text,
  products text,
  grade text not null default 'B' check (grade in ('A','B','C')),
  profile text,
  grade_reason text,
  stage text not null default '新询盘',
  last_contact date,
  next_follow date,
  concern text,
  next_action text,
  probability integer default 50 check (probability between 0 and 100),
  amount numeric(12,2),
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 兼容你之前已创建的 customers 表
alter table public.customers add column if not exists country text;
alter table public.customers add column if not exists products text;
alter table public.customers add column if not exists grade_reason text;

create table if not exists public.followups (
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid(),
 customer_id bigint not null references public.customers(id) on delete cascade,
 contact_date timestamptz default now(),
 channel text, customer_message text, our_message text, summary text,
 concern text, next_action text, next_follow date,
 created_at timestamptz default now()
);

create table if not exists public.quotes (
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid(),
 customer_id bigint not null references public.customers(id) on delete cascade,
 number text, amount numeric(12,2), status text default '草稿', notes text,
 created_at timestamptz default now()
);
create table if not exists public.pis (
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid(),
 customer_id bigint not null references public.customers(id) on delete cascade,
 number text, amount numeric(12,2), status text default '待确认', notes text,
 created_at timestamptz default now()
);
create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid(),
 customer_id bigint not null references public.customers(id) on delete cascade,
 number text, amount numeric(12,2), status text default '待生产', notes text,
 created_at timestamptz default now()
);
create table if not exists public.shipments (
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid(),
 customer_id bigint not null references public.customers(id) on delete cascade,
 tracking_no text, carrier text, status text default '待发货', notes text,
 created_at timestamptz default now()
);
create table if not exists public.samples (
 id bigint generated by default as identity primary key,
 user_id uuid not null default auth.uid(),
 customer_id bigint not null references public.customers(id) on delete cascade,
 item text, tracking_no text, status text default '准备中', notes text,
 created_at timestamptz default now()
);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;
drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers for each row execute function public.set_updated_at();

alter table public.customers enable row level security;
alter table public.followups enable row level security;
alter table public.quotes enable row level security;
alter table public.pis enable row level security;
alter table public.orders enable row level security;
alter table public.shipments enable row level security;
alter table public.samples enable row level security;

do $$
declare t text;
begin
 foreach t in array array['customers','followups','quotes','pis','orders','shipments','samples']
 loop
   execute format('drop policy if exists "own_select" on public.%I',t);
   execute format('drop policy if exists "own_insert" on public.%I',t);
   execute format('drop policy if exists "own_update" on public.%I',t);
   execute format('drop policy if exists "own_delete" on public.%I',t);
   execute format('create policy "own_select" on public.%I for select to authenticated using (auth.uid()=user_id)',t);
   execute format('create policy "own_insert" on public.%I for insert to authenticated with check (auth.uid()=user_id)',t);
   execute format('create policy "own_update" on public.%I for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id)',t);
   execute format('create policy "own_delete" on public.%I for delete to authenticated using (auth.uid()=user_id)',t);
 end loop;
end $$;

create index if not exists customers_user_follow_idx on public.customers(user_id,next_follow);
create index if not exists followups_customer_idx on public.followups(customer_id,contact_date desc);
