-- PACKROVE CRM V2 -> V9.5.2 兼容升级
-- 作用：保留旧客户数据，补齐新版字段和表，不删除现有数据。
-- 可重复执行。
-- 请在 Supabase Dashboard -> SQL Editor -> New query 中完整执行。

begin;

create extension if not exists pgcrypto;

-- 1. 补齐旧 customers 表缺少的新版字段
alter table public.customers add column if not exists platform text default '';
alter table public.customers add column if not exists country text default '';
alter table public.customers add column if not exists city text default '';
alter table public.customers add column if not exists website text default '';
alter table public.customers add column if not exists instagram text default '';
alter table public.customers add column if not exists email text default '';
alter table public.customers add column if not exists contact_name text default '';
alter table public.customers add column if not exists customer_type text default '';
alter table public.customers add column if not exists customer_pool text default '未建联';
alter table public.customers add column if not exists target_product text default '';
alter table public.customers add column if not exists recommended_product text default '';
alter table public.customers add column if not exists outreach_angle text default '';
alter table public.customers add column if not exists level text default 'C';
alter table public.customers add column if not exists touch_status text default '未联系';
alter table public.customers add column if not exists grade_reason text default '';
alter table public.customers add column if not exists requirement text default '';
alter table public.customers add column if not exists quantity text default '';
alter table public.customers add column if not exists budget text default '';
alter table public.customers add column if not exists concern text default '';
alter table public.customers add column if not exists next_action text default '';
alter table public.customers add column if not exists next_follow date;
alter table public.customers add column if not exists probability integer default 0;
alter table public.customers add column if not exists notes text default '';
alter table public.customers add column if not exists last_contact date;
alter table public.customers add column if not exists profile text default '';
alter table public.customers add column if not exists stage text default '需求确认';
alter table public.customers add column if not exists created_at timestamptz default now();
alter table public.customers add column if not exists updated_at timestamptz default now();

-- 2. 把V2字段内容迁移到V9.5字段
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='customers' and column_name='grade'
  ) then
    execute $q$
      update public.customers
      set level = case
        when grade in ('A','B','C') then grade
        else coalesce(nullif(level,''),'C')
      end
      where level is null or level='' or level='C'
    $q$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='customers' and column_name='products'
  ) then
    execute $q$
      update public.customers
      set target_product = coalesce(nullif(target_product,''), products, ''),
          recommended_product = coalesce(nullif(recommended_product,''), products, '')
    $q$;
  end if;
end $$;

update public.customers
set customer_pool =
  case
    when customer_pool in ('未建联','已建联') then customer_pool
    when coalesce(touch_status,'') in ('已回复','一触完成','二触完成','三触完成') then '已建联'
    else '未建联'
  end;

update public.customers
set touch_status =
  case
    when touch_status in ('未联系','一触完成','二触完成','三触完成','已回复') then touch_status
    when customer_pool='已建联' then '已回复'
    else '未联系'
  end;

update public.customers
set level = case when level in ('A','B','C') then level else 'C' end,
    stage = coalesce(nullif(stage,''),'需求确认'),
    updated_at = coalesce(updated_at,now());

-- 3. 新版沟通时间轴
create table if not exists public.timeline (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  customer_id bigint not null references public.customers(id) on delete cascade,
  event_date date not null default current_date,
  event_type text default '跟进',
  content text not null,
  created_at timestamptz not null default now()
);

-- 4. 新版报价表（V2原来叫 quotes）
create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  customer_id bigint not null references public.customers(id) on delete cascade,
  quote_no text not null,
  product text default '',
  quantity numeric default 0,
  unit_price numeric default 0,
  amount numeric default 0,
  currency text default 'USD',
  issue_date date default current_date,
  valid_until date,
  status text default '草稿',
  notes text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. 新版PI表（V2原来叫 pis）
create table if not exists public.pi_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  customer_id bigint not null references public.customers(id) on delete cascade,
  quotation_id bigint references public.quotations(id) on delete set null,
  pi_no text not null,
  amount numeric default 0,
  currency text default 'USD',
  payment_method text default 'T/T',
  issue_date date default current_date,
  status text default '待确认',
  created_at timestamptz default now()
);

-- 6. 补齐V2 orders表缺少的新版字段
alter table public.orders add column if not exists pi_id bigint references public.pi_documents(id) on delete set null;
alter table public.orders add column if not exists order_no text;
alter table public.orders add column if not exists product text default '';
alter table public.orders add column if not exists quantity text default '';
alter table public.orders add column if not exists currency text default 'USD';
alter table public.orders add column if not exists payment_status text default '待付款';
alter table public.orders add column if not exists production_status text default '待生产';
alter table public.orders add column if not exists delivery_date date;
alter table public.orders add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='orders' and column_name='number'
  ) then
    execute $q$
      update public.orders
      set order_no = coalesce(nullif(order_no,''), nullif(number,''), 'V2-PO-' || id::text)
    $q$;
  else
    update public.orders
    set order_no = coalesce(nullif(order_no,''), 'V2-PO-' || id::text);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='orders' and column_name='status'
  ) then
    execute $q$
      update public.orders
      set production_status = coalesce(nullif(production_status,''), status, '待生产')
    $q$;
  end if;
end $$;

-- 7. 补齐V2 shipments表缺少的新版字段
alter table public.shipments add column if not exists order_id bigint references public.orders(id) on delete cascade;
alter table public.shipments add column if not exists method text default '';
alter table public.shipments add column if not exists eta date;
alter table public.shipments add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='shipments' and column_name='carrier'
  ) then
    execute $q$
      update public.shipments
      set method = coalesce(nullif(method,''), carrier, '')
    $q$;
  end if;
end $$;

-- 8. 将V2旧报价和PI复制到新版表（避免重复）
do $$
begin
  if to_regclass('public.quotes') is not null then
    execute $q$
      insert into public.quotations
        (user_id,customer_id,quote_no,amount,status,notes,created_at,updated_at)
      select
        q.user_id,q.customer_id,
        coalesce(nullif(q.number,''),'V2-Q-' || q.id::text),
        coalesce(q.amount,0),coalesce(q.status,'草稿'),coalesce(q.notes,''),
        coalesce(q.created_at,now()),coalesce(q.created_at,now())
      from public.quotes q
      where not exists (
        select 1 from public.quotations n
        where n.user_id=q.user_id
          and n.quote_no=coalesce(nullif(q.number,''),'V2-Q-' || q.id::text)
      )
    $q$;
  end if;

  if to_regclass('public.pis') is not null then
    execute $q$
      insert into public.pi_documents
        (user_id,customer_id,pi_no,amount,status,created_at)
      select
        p.user_id,p.customer_id,
        coalesce(nullif(p.number,''),'V2-PI-' || p.id::text),
        coalesce(p.amount,0),coalesce(p.status,'待确认'),
        coalesce(p.created_at,now())
      from public.pis p
      where not exists (
        select 1 from public.pi_documents n
        where n.user_id=p.user_id
          and n.pi_no=coalesce(nullif(p.number,''),'V2-PI-' || p.id::text)
      )
    $q$;
  end if;
end $$;

-- 9. 更新时间触发器
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end $$;

drop trigger if exists customers_updated_at on public.customers;
drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists quotations_updated_at on public.quotations;
create trigger quotations_updated_at
before update on public.quotations
for each row execute function public.set_updated_at();

-- 10. 索引
create index if not exists customers_next_follow_idx on public.customers(next_follow);
create index if not exists customers_pool_idx on public.customers(customer_pool);
create index if not exists customers_stage_idx on public.customers(stage);
create index if not exists timeline_customer_idx on public.timeline(customer_id,event_date desc);

-- 11. RLS：每个登录账号只访问自己的数据
alter table public.customers enable row level security;
alter table public.timeline enable row level security;
alter table public.quotations enable row level security;
alter table public.pi_documents enable row level security;
alter table public.orders enable row level security;
alter table public.shipments enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'customers','timeline','quotations','pi_documents','orders','shipments'
  ] loop
    execute format('drop policy if exists authenticated_all on public.%I',t);
    execute format('drop policy if exists own_select on public.%I',t);
    execute format('drop policy if exists own_insert on public.%I',t);
    execute format('drop policy if exists own_update on public.%I',t);
    execute format('drop policy if exists own_delete on public.%I',t);

    execute format(
      'create policy own_select on public.%I for select to authenticated using (auth.uid()=user_id)',t
    );
    execute format(
      'create policy own_insert on public.%I for insert to authenticated with check (auth.uid()=user_id)',t
    );
    execute format(
      'create policy own_update on public.%I for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id)',t
    );
    execute format(
      'create policy own_delete on public.%I for delete to authenticated using (auth.uid()=user_id)',t
    );
  end loop;
end $$;

grant usage on schema public to authenticated;
grant select,insert,update,delete on public.customers to authenticated;
grant select,insert,update,delete on public.timeline to authenticated;
grant select,insert,update,delete on public.quotations to authenticated;
grant select,insert,update,delete on public.pi_documents to authenticated;
grant select,insert,update,delete on public.orders to authenticated;
grant select,insert,update,delete on public.shipments to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;

-- 通知 Supabase/PostgREST 立即刷新表结构缓存
notify pgrst, 'reload schema';
