window.PACKROVE_SEED_CUSTOMERS = [
  {
    "id": "local-1",
    "name": "ILAN Francamente Kombucha",
    "platform": "WA",
    "country": "哥伦比亚",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "自动封罐机",
    "recommended_product": "自动封罐机",
    "outreach_angle": "",
    "level": "A",
    "stage": "报价",
    "touch_status": "已回复",
    "profile": "创业型饮品客户，主动询问自动设备，对进口和清关流程较谨慎。",
    "grade_reason": "设备客单价高、互动积极、需求明确；当前主要障碍是进口顾虑。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "进口、清关、税费及到门方案",
    "next_action": "确认客户更倾向快递还是海运，并解释DDP/到门方案差异。",
    "next_follow": "2026-07-23",
    "probability": 80,
    "notes": "客户对进口有顾虑，已发送报价。",
    "last_contact": "2026-07-22",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-2",
    "name": "Renato Crevelim",
    "platform": "WA",
    "country": "巴西",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "带传送带封罐机",
    "recommended_product": "带传送带封罐机",
    "outreach_angle": "",
    "level": "A",
    "stage": "PI",
    "touch_status": "已回复",
    "profile": "巴西设备客户，已确认PI，正在让货代核实运输。",
    "grade_reason": "已进入实质执行阶段，成交意向很强。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "货代确认、运输衔接",
    "next_action": "询问货代确认进度，主动提供包装尺寸、重量和装运资料。",
    "next_follow": "2026-07-25",
    "probability": 95,
    "notes": "已发草稿PI，客户正在让货代确认运费。",
    "last_contact": "2026-07-22",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-3",
    "name": "Moon Crafts",
    "platform": "IG",
    "country": "",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "手动封罐机；250B/500A/500B/700A",
    "recommended_product": "手动封罐机；250B/500A/500B/700A",
    "outreach_angle": "",
    "level": "B",
    "stage": "报价",
    "touch_status": "已回复",
    "profile": "手动封罐机客户，已明确表示8月初有采购需求。",
    "grade_reason": "有明确时间节点和产品兴趣，但尚未进入最终确认。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "采购时间尚未完全锁定",
    "next_action": "提前确认8月采购计划，询问是否需要更新报价或确认具体罐型。",
    "next_follow": "2026-07-25",
    "probability": 65,
    "notes": "8月初有需求。",
    "last_contact": "2026-07-15",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-4",
    "name": "Brian",
    "platform": "WA",
    "country": "牙买加",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "A1 2色Logo 1000个",
    "recommended_product": "A1 2色Logo 1000个",
    "outreach_angle": "",
    "level": "B",
    "stage": "报价",
    "touch_status": "已回复",
    "profile": "牙买加新店客户，计划9月底开业，需要定制罐子。",
    "grade_reason": "有明确开业节点、数量和定制需求。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "交期、海运周期、开业时间",
    "next_action": "询问Logo和开业准备进度，并提醒生产与约70天运输周期。",
    "next_follow": "2026-07-27",
    "probability": 65,
    "notes": "客户在考虑，9月底开业。",
    "last_contact": "2026-07-22",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-5",
    "name": "GrabThaLook",
    "platform": "IG",
    "country": "圭亚那",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "手动封罐机",
    "recommended_product": "手动封罐机",
    "outreach_angle": "",
    "level": "B",
    "stage": "需求确认",
    "touch_status": "已回复",
    "profile": "曾对手动设备感兴趣，近期沟通停顿。",
    "grade_reason": "存在真实兴趣但需求尚未完全确认。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "运输时间长、需求是否已解决",
    "next_action": "轻松询问近况及之前的设备需求是否已经解决。",
    "next_follow": "2026-07-25",
    "probability": 50,
    "notes": "运输时间较长。",
    "last_contact": "2026-07-22",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-6",
    "name": "Coco's Dessert Factory",
    "platform": "IG",
    "country": "英国",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "A2罐子10000个；500ml杯+纸碗",
    "recommended_product": "A2罐子10000个；500ml杯+纸碗",
    "outreach_angle": "",
    "level": "B",
    "stage": "报价",
    "touch_status": "已回复",
    "profile": "英国甜品店客户，同时有罐子、杯子和纸碗的组合采购需求。",
    "grade_reason": "需求品类多、数量明确，具备较高订单价值；但报价后已读未回。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "价格、组合方案或采购优先级",
    "next_action": "询问报价中是否有需要调整的数量、印刷或运输方案。",
    "next_follow": "2026-07-25",
    "probability": 50,
    "notes": "已读未回。",
    "last_contact": "2026-07-22",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-7",
    "name": "Brandon",
    "platform": "WA",
    "country": "",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "A2罐子1000个",
    "recommended_product": "A2罐子1000个",
    "outreach_angle": "",
    "level": "C",
    "stage": "报价",
    "touch_status": "已回复",
    "profile": "有明确罐型和数量需求，但报价后暂无进一步互动。",
    "grade_reason": "客户热度和回复意愿偏低。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "价格或采购时机",
    "next_action": "简短确认是否看过报价，以及是否需要调整数量或印刷。",
    "next_follow": "2026-07-25",
    "probability": 35,
    "notes": "已读未回。",
    "last_contact": "2026-07-20",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-8",
    "name": "Fer",
    "platform": "WA",
    "country": "",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "A13 2色Logo 1000个",
    "recommended_product": "A13 2色Logo 1000个",
    "outreach_angle": "",
    "level": "C",
    "stage": "报价",
    "touch_status": "已回复",
    "profile": "定制罐子询盘客户，数量明确，但报价后尚未阅读。",
    "grade_reason": "缺少有效互动信号，需低频确认。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "消息未读、需求真实性待确认",
    "next_action": "确认客户是否收到报价，避免连续发送过多信息。",
    "next_follow": "2026-07-25",
    "probability": 20,
    "notes": "报价消息未读。",
    "last_contact": "2026-07-20",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  },
  {
    "id": "local-9",
    "name": "Fable Coffee Cart Central PA",
    "platform": "IG",
    "country": "美国",
    "city": "",
    "website": "",
    "instagram": "",
    "email": "",
    "contact_name": "",
    "customer_type": "",
    "customer_pool": "已建联",
    "target_product": "12oz杯 2色环绕印刷",
    "recommended_product": "12oz杯 2色环绕印刷",
    "outreach_angle": "",
    "level": "C",
    "stage": "需求确认",
    "touch_status": "已回复",
    "profile": "美国咖啡车客户，关注杯子印刷，但认为综合成本及运输时间不理想。",
    "grade_reason": "近期采购意愿较低，应降低频率、长期培育。",
    "requirement": "",
    "quantity": "",
    "budget": "",
    "concern": "综合价格、海运时效",
    "next_action": "分享新案例或更合适的组合方案，保持低频存在感。",
    "next_follow": "2026-07-30",
    "probability": 20,
    "notes": "综合看比当地价格低，但整体时效晚约10天。",
    "last_contact": "2026-07-20",
    "created_at": "2026-07-22T00:00:00Z",
    "updated_at": "2026-07-22T00:00:00Z"
  }
];
